CREATE TABLE IF NOT EXISTS Referral_excerpts
(
	id INT NOT NULL AUTO_INCREMENT PRIMARY_KEY,
	referral INT,
	body TEXT NOT NULL,
	FOREIGN KEY (referral) REFERENCES Referrals(id) ON DELETE CASCADE ON UPDATE CASCADE,
);
